#pragma once

#define EE_HANDS
#define VIAL_KEYBOARD_UID {0xa1, 0x8b, 0x9b, 0x77, 0x32, 0x7e, 0x7a, 0x6c}
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define WHEEL_EXTENDED_REPORT
#define MOUSE_EXTENDED_REPORT

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 4

#define VIAL_DEFAULT_TAPPING 2
