// Generated by Vial Keymap C Editor (https://vial-keymap-c-editor.pages.dev)

#include QMK_KEYBOARD_H

#ifdef QMK_SETTINGS
#include "qmk_settings.h"
#endif

/* USER INCLUDE BEGIN */
#include "quantum.h"
#include "pointing_device.h"
#include "tb.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h> // abs
/* USER INCLUDE END */

/* GENERATED CODE BEGIN */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
                /* 左手側 */
                   KC_Q,            KC_W,            KC_E,            KC_R,            KC_T,                QK_BOOT,      
                   LT(3,KC_A),      KC_S,            KC_D,            KC_F,            KC_G,                KC_NO,
                   LSFT_T(KC_Z),    KC_X,            KC_C,            KC_V,            KC_B,     
                   KC_LEFT_GUI,                                       KC_LEFT_ALT,     LT(1,KC_LANGUAGE_2), LT(5,KC_ENTER),        
                /* 右手側 */
                QK_BOOT,            
                   KC_Y,            KC_U,            KC_I,            KC_O,            KC_P,  
                KC_NO,
                   KC_H,            KC_J,            KC_K,            LT(4,KC_L),      KC_SEMICOLON,            
                   KC_N,            KC_M,            KC_COMMA,        KC_DOT,          RSFT_T(KC_SLASH),  
                   LT(6,KC_SPACE),     LT(2,KC_LANGUAGE_1),                            KC_ESCAPE
    ),
    [1] = LAYOUT(
                /* 左手側 */
                   KC_ESCAPE,       (QK_LGUI|KC_W),  (QK_LGUI|KC_E),  (QK_LGUI|KC_R),  (QK_LGUI|KC_T),       KC_TRANSPARENT,  
                   (QK_LGUI|KC_A),  (QK_LGUI|KC_S),  (QK_LGUI|KC_D),  (QK_LGUI|KC_F),  (QK_LGUI|KC_G),       KC_TRANSPARENT,
                   (QK_LGUI|KC_Z),  (QK_LGUI|KC_X),  (QK_LGUI|KC_C),  (QK_LGUI|KC_V),  (QK_LGUI|KC_B),  
                   KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,       (QK_LGUI|KC_ENTER),  
                /* 右手側 */
                KC_TRANSPARENT,  
                   (QK_LSFT|KC_6),  (QK_LSFT|KC_7),  (QK_LSFT|KC_8),  (QK_LSFT|KC_9),  KC_MINUS, 
                KC_TRANSPARENT,
                   (QK_LGUI|KC_H),  (QK_LGUI|KC_J),  (QK_LGUI|KC_K),  (QK_LGUI|KC_L),  KC_EQUAL,
                   (QK_LGUI|KC_N),  (QK_LGUI|KC_M), (QK_LGUI|KC_COMMA),(QK_LGUI|KC_DOT), (QK_LSFT|KC_INTERNATIONAL_1), 
                   (QK_LGUI|KC_SPACE),  KC_TRANSPARENT,                                KC_TRANSPARENT
    ),
    [2] = LAYOUT(
                /* 左手側 */
                   KC_1,            KC_KP_2,         KC_KP_3,         KC_KP_4,         KC_KP_5,              KC_TRANSPARENT,
                   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,       KC_TRANSPARENT,
                   KC_LEFT_SHIFT,   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                   KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,       KC_TRANSPARENT, 
                /* 右手側 */
                KC_TRANSPARENT,     
                   KC_KP_6,         KC_KP_7,         KC_KP_8,         KC_KP_9,         KC_KP_0,  
                KC_TRANSPARENT,
                   KC_LEFT,         KC_DOWN,           KC_UP,        KC_RIGHT,         KC_TRANSPARENT,  
                   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT, KC_TRANSPARENT,   KC_RIGHT_SHIFT,  
                   KC_TRANSPARENT,  KC_TRANSPARENT,                                    KC_TRANSPARENT
    ),
    [3] = LAYOUT(
                /* 左手側*/
                   KC_Q,            (QK_LCTL|KC_W),  (QK_LCTL|KC_E),  (QK_LCTL|KC_R),  (QK_LCTL|KC_T),        KC_TRANSPARENT,  
                   KC_TRANSPARENT,  (QK_LGUI|KC_LEFT),(QK_LCTL|KC_D),  KC_RIGHT,       (QK_LCTL|KC_G),        KC_TRANSPARENT,
                   (QK_LCTL|KC_Z),  (QK_LCTL|KC_X),  (QK_LCTL|KC_C),  (QK_LCTL|KC_V),  KC_LEFT,  
                   KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,       (QK_LCTL|KC_ENTER),  
                /* 右手側 */
                KC_TRANSPARENT,  
                   (QK_LCTL|KC_Y),  (QK_LCTL|KC_U),  (QK_LCTL|KC_I),  (QK_LCTL|KC_O),  KC_UP,
                KC_TRANSPARENT,
                   KC_BACKSPACE,    (QK_LCTL|KC_J),  (QK_LCTL|KC_K),  (QK_LCTL|KC_L),  (QK_LCTL|KC_SEMICOLON),        
                   KC_DOWN,         (QK_LCTL|KC_M),  (QK_LCTL|KC_COMMA),(QK_LCTL|KC_DOT),(QK_LCTL|KC_SLASH),
                   (QK_LCTL|KC_SPACE),  KC_TRANSPARENT,                                 KC_TRANSPARENT
    ),
    [4] = LAYOUT(
                /* 左手側 */
                   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                   KC_LEFT_CTRL,    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                   KC_LEFT_SHIFT,   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                   KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                /* 右手側 */
                KC_TRANSPARENT, 
                   (QK_LCTL|KC_BACKSLASH), (QK_LCTL|QK_LGUI|KC_I),    KC_MISSION_CONTROL,  (QK_LSFT|KC_L),  KC_TRANSPARENT,  
                KC_TRANSPARENT,
                   (QK_LSFT|KC_H),      KC_MS_BTN1,      KC_MS_BTN2,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                   KC_TRANSPARENT,  KC_TRANSPARENT,                                    KC_TRANSPARENT
    ),
    [5] = LAYOUT(
                 /* 左手側 */
                    KC_ESCAPE,      KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT, KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                    KC_LEFT_SHIFT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT,                                   KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                /* 右手側*/
                KC_TRANSPARENT, 
                    KC_TRANSPARENT,  KC_TRANSPARENT, KC_TRANSPARENT, (QK_LSFT|KC_RIGHT_BRACKET), KC_RIGHT_BRACKET,
                KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT, (QK_LSFT|KC_BACKSLASH),   KC_BACKSLASH,  
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT, (QK_LSFT|KC_INTERNATIONAL_1),  
                    KC_TRANSPARENT,  KC_TRANSPARENT,                                   KC_TRANSPARENT
    ),
    [6] = LAYOUT(
               /* 左手側 */
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT, 
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                /* 右手側 */
                KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT, (QK_LSFT|KC_LEFT_BRACKET), KC_LEFT_BRACKET, 
                KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  (QK_LSFT|KC_QUOTE),  
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_INT1,  
                    KC_TRANSPARENT,  KC_TRANSPARENT,                                    KC_TRANSPARENT
    ),
    [7] = LAYOUT(
                /* 左手側*/
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                    KC_TRANSPARENT,                                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                /* 右手側 */
                KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                KC_TRANSPARENT,
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  
                    KC_TRANSPARENT,  KC_TRANSPARENT,                                    KC_TRANSPARENT
    )
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
};
#endif

// Tap Dance definitions
#define TAP_DANCE_ENTRY(onTap, onHold, onDoubleTap, onTapHold, tappingTerm) ((vial_tap_dance_entry_t){.on_tap = onTap, .on_hold = onHold, .on_double_tap = onDoubleTap, .on_tap_hold = onTapHold, .custom_tapping_term = tappingTerm})
#if VIAL_TAP_DANCE_ENTRIES > 0
const vial_tap_dance_entry_t default_tap_dance_entries[] = {
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200)
};
#endif

// Combo definitions
#define COMBO_ENTRY(k1, k2, k3, k4, result) ((vial_combo_entry_t){.input ={k1, k2, k3, k4}, .output = result})
#if VIAL_COMBO_ENTRIES > 0
const vial_combo_entry_t PROGMEM default_combo_entries[] = {
    COMBO_ENTRY(KC_Q,  KC_W,  KC_NO, KC_NO, KC_TAB),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
#endif

// Macro buffer
const uint8_t PROGMEM default_macro_buffer[] = {
    
};

// Key Override definitions
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
const vial_key_override_entry_t default_key_override_entries[] = {
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    }
};
#endif

// Initialize Vial dynamic items
void __real_dynamic_keymap_reset(void);
void __wrap_dynamic_keymap_reset(void) {
    __real_dynamic_keymap_reset();

#if VIAL_TAP_DANCE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_tap_dance_entries) / sizeof(default_tap_dance_entries[0]); ++i) {
        dynamic_keymap_set_tap_dance(i, &default_tap_dance_entries[i]);
    }
#endif
#if VIAL_COMBO_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_combo_entries) / sizeof(default_combo_entries[0]); ++i) {
        dynamic_keymap_set_combo(i, &default_combo_entries[i]);
    }
#endif
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_key_override_entries) / sizeof(default_key_override_entries[0]); ++i) {
        dynamic_keymap_set_key_override(i, &default_key_override_entries[i]);
    }
#endif
#ifdef QMK_SETTINGS
    qmk_settings_t qs;
    uint8_t* p_qs = (uint8_t*)&qs;
    for (size_t i = 0; i < sizeof(qs); ++i) {
        p_qs[i] = dynamic_keymap_get_qmk_settings(i);
    }
    #ifdef VIAL_DEFAULT_TAPPING
        qs.tapping = VIAL_DEFAULT_TAPPING;
    #endif
    #ifdef VIAL_DEFAULT_AUTO_SHIFT
        qs.auto_shift = VIAL_DEFAULT_AUTO_SHIFT;
    #endif
    #ifdef DEFAULT_GRAVE_ESC_OVERRIDE
        qs.grave_esc_override = DEFAULT_GRAVE_ESC_OVERRIDE;
    #endif

    for (size_t i = 0; i < sizeof(qs); ++i) {
        dynamic_keymap_set_qmk_settings(i, p_qs[i]);
    }

    #ifdef DEFAULT_KEYMAP_EECONFIG
        keymap_config.raw = DEFAULT_KEYMAP_EECONFIG;
        eeconfig_update_keymap(keymap_config.raw);
    #endif

    qmk_settings_init();
#endif 

    uint16_t const macro_buffer_size = MIN(sizeof(default_macro_buffer), dynamic_keymap_macro_get_buffer_size());
    dynamic_keymap_macro_set_buffer(0, macro_buffer_size, (uint8_t *)default_macro_buffer);
}

/* GENERATED CODE END */


/* USER CODE BEGIN */
void keyboard_post_init_user(void) { tb_init(); }
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  return tb_process_record(keycode, record);
}
report_mouse_t pointing_device_task_combined_user(report_mouse_t l, report_mouse_t r) {
  return tb_task_combined(l, r);
}
/* USER CODE END */